config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {
    sign_in: 'sign_in',
    sign_out: 'sign_out',
    password: 'password',
    confirmation: 'confirmation',
    unlock: 'unlock',
    registration: 'registration',
    sign_up: 'sign_up'
  }, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    # passwords: 'custom_passwords',
    confirmations: 'users/confirmations',
    # unlocks: 'custom_unlocks'
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "albums#index_feed"
  get "feeds/photos", to: "photos#index_feed"
  get "pending", to: "pending_users#index"
  scope module: "admin" do
    get "authorizations", to: "authorizations#index"
    get "unauthorized", to: "unauthorizations#index"
  end
  # scope "guest" do
  #   get "authorizations", to: "authorizations#index", as: "guest_authorizations"
  #   get "unauthorized", to: "unauthorizations#index", as: "guest_unauthorizations"
  # end

  # namespace :guest do
  #   get "authorizations", to: "authorizations#index"
  #   get "unauthorized", to: "unauthorizations#index"
  # end
  scope "discovers" do
    get "/", to: "albums#index_discover", as: "discover"
    get "/photos", to: "photos#index_discover", as: "discover_photos"
    get "/photos/:id", to: "photos#discover_user_photos_index", as: "discover_photo"
    get "/albums/:id", to: "albums#discover_user_index", as: "discover_album"
    get "/followees/:id", to: "followees#discover_followee_index", as: "discover_followee"
    get "/followers/:id", to: "followers#discover_follower_index", as: "discover_follower"
  end
  resources :photos, :albums
  resources :followees, only: [:index, :create, :destroy]
  resources :followers, only: [:index, :create, :destroy]
  resources :profiles , only: [:edit, :update]
  resources :passwords , only: [:edit, :update]
  resources :likes, only: [:create, :destroy]
  get 'search', to: "search#index"

  namespace :admin do
    resources :photos, :albums, :users
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @followers = Follower.where(follower_id: current_user.id)
    album_query = Album.order(updated_at: :desc).where(is_public: true).includes(:user).ransack(params[:q])
    @likes_album = Like.where(likeable_type: 'Album')

    photo_query = Photo.order(updated_at: :desc).where(is_public: true).includes(:user).ransack(params[:q])
    @likes_photo = Like.where(likeable_type: 'Photo')
    @albums = album_query.result(distinct: true)
    @photos = photo_query.result(distinct: true)
    @result = @albums + @photos
    @result = @result.sort_by { |record| record.updated_at }.reverse
    @result = Kaminari.paginate_array(@result).page(params[:page]).per(4)
  end
end

app/helpers/search/albums_helper.rb
module Search::AlbumsHelper
end

app/helpers/search/photos_helper.rb
module Search::PhotosHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_form.html.slim
= search_form_for(@query, url: search_path, method: :get,remote: true, class: "d-flex") do |f|
    = f.search_field :title_or_description_or_user_first_name_cont, placeholder: "Search...", class: "form-control w-75"
    = f.submit "Search", class:"btn btn-success"

app/views/search/index.html.slim
div class="main__content__album bg-white mt-4 d-flex justify-around flex-column"
    div class="main__album d-flex flex-column"
        div class="container pt-5"
            div class="row parent-node"
                / <!-- start template -->
                - @result.each do |record|
                    div class="col-sm-12 col-md-6 mx-3 my-2 p-0 album bg-body-tertiary shadow border-0 button-modal child-node d-flex align-items-center" id="album_#{record["id"]}"
                        / <!-- remember to add album_id -->
                        div.row.w-100.wrapper.justify-content-between
                            div class="photo__wrapper d-flex align-items-center col-md-4 postion-relative" id="photo_#{record["id"]}" data-bs-toggle="modal" data-bs-target="#photoModal"
                                / <!-- remember to add photo_id -->
                                - if !record["album_attachments"].nil?
                                    - record.album_attachments.each do |image|
                                        div.photo.position-absolute
                                            img src="#{image.url}" alt=""
                                - else
                                    div.photo.position-absolute
                                        img src="#{record.img_url.url}" alt=""
                            div class="col-md-7 photo__info d-flex flex-column justify-content-between"
                                div class="photo__author d-flex align-items-center justify-content-between"
                                    a href="#{discover_photos_path}/#{record.user.id}" class="d-flex align-items-center"
                                        div class="header-box__info__img" href="#"
                                            img src="#{record.user.img_url.present? ? record.user.img_url.url : '/assets/avatar.png'}" alt="courage-dog"
                                        div class="photo__author__name ms-3 text-primary" = record.user.first_name.to_s.humanize + ' ' + record.user.last_name.to_s.humanize
                                    = render partial: "shared/button/follow/discover", locals: { asset: record, followers: @followers, type_asset: record.class }
                                h5.photo__title.fw-bold = record["title"]
                                p.photo__description.text-start = record["description"]
                                div.photo__liked.d-flex.justify-content-between.align-items-center
                                    - likes = record.class == 'Album' ? @likes_album : @likes_photo
                                    = render partial: "shared/button/like", locals: { asset: record, likes: likes, type_asset: record.class }
                                    p.photo__time.m-0 = record["created_at"].in_time_zone("Asia/Ho_Chi_Minh").strftime("%H:%M %P %d/%m/%Y")
                / <!-- end template -->
                = render partial: "shared/pagination", locals: { asset: @result}
                / <!-- end template -->