config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {
    sign_in: 'sign_in',
    sign_out: 'sign_out',
    password: 'password',
    confirmation: 'confirmation',
    unlock: 'unlock',
    registration: 'registration',
    sign_up: 'sign_up'
  }, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    # passwords: 'custom_passwords',
    confirmations: 'users/confirmations',
    # unlocks: 'custom_unlocks'
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "albums#index_feed"
  get "feeds/photos", to: "photos#index_feed"
  get "pending", to: "pending_users#index"
  scope module: "admin" do
    get "authorizations", to: "authorizations#index"
    get "unauthorized", to: "unauthorizations#index"
  end
  # scope "guest" do
  #   get "authorizations", to: "authorizations#index", as: "guest_authorizations"
  #   get "unauthorized", to: "unauthorizations#index", as: "guest_unauthorizations"
  # end

  # namespace :guest do
  #   get "authorizations", to: "authorizations#index"
  #   get "unauthorized", to: "unauthorizations#index"
  # end
  scope "discovers" do
    get "/", to: "albums#index_discover", as: "discover"
    get "/photos", to: "photos#index_discover", as: "discover_photos"
    get "/photos/:id", to: "photos#discover_user_photos_index", as: "discover_photo"
    get "/albums/:id", to: "albums#discover_user_index", as: "discover_album"
    get "/followees/:id", to: "followees#discover_followee_index", as: "discover_followee"
    get "/followers/:id", to: "followers#discover_follower_index", as: "discover_follower"
  end
  resources :photos, :albums
  resources :followees, only: [:index, :create, :destroy]
  resources :followers, only: [:index, :create, :destroy]
  resources :profiles , only: [:edit, :update]
  resources :passwords , only: [:edit, :update]
  resources :likes, only: [:create, :destroy]
  get 'search', to: "search#index"

  namespace :admin do
    resources :photos, :albums, :users
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_many :likes, as: :likeable, dependent: :delete_all
  has_many :liking_users, through: :likes, source: :user

  mount_uploader :img_url, PhotoUploader

  validates :img_url, presence: {message: "Photo is required"}
  validates :title, presence: {message: "Title is required"}
  validates :is_public, inclusion: { in: [true, false], allow_nil: true }

  def self.ransackable_attributes(auth_object = nil)
    ["description", "title", "user_id"]
  end
  def self.ransackable_associations(auth_object = nil)
    ["likes", "liking_users", "user"]
  end
end

app/controllers/admin/photos_controller.rb
class Admin::PhotosController < Admin::AuthorizationsController
  def index
    @photos = Photo.order(updated_at: :desc).page(params[:page]).per(10)
  end

  def edit
    @photo = Photo.find_by(id: params["id"])
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :check_user_status
  before_action :check_user
  def index
    @photos = Photo.where(user_id: current_user.id).order(updated_at: :desc).page(params[:page]).per(8)
    query_navbar(current_user.id)
    @albums = Album.where(user_id: current_user.id)
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      redirect_to discover_photo_path(@photo.user_id), notice: "Photo created successfully"
    else
      respond_to do |format|
        format.html { render 'new' }
      end
    end
  end

  def edit
    @photo = Photo.find_by(id: params["id"])
  end

  def update
    @photo = Photo.find_by(id: params["id"])
    if @photo.update(photo_params)
      redirect_to discover_photo_path(@photo.user_id)
    else
      render 'edit'
    end
  end

  def destroy
    @photo = Photo.find(params["id"])
    @photo.destroy
    respond_to do |format|
      format.js {render inline: "location.reload();" }
    end
  end

  def discover_user_photos_index
    @photos = Photo.where(user_id: params["id"]).where(is_public: true).order(updated_at: :desc).page(params[:page]).per(8)
    query_navbar(params[:id])
    @albums = Album.where(user_id: params["id"]).where(is_public: true)
    render "photos/discover_user_photos/index"
  end

  def index_discover
    @photos = Photo.includes(:user).order(updated_at: :desc).where(is_public: true).page(params[:page]).per(4)
    @followers = Follower.where(follower_id: current_user.id)
    @likes = Like.where(likeable_type: 'Photo')
    render "public/discover_photos/index"
  end

  def index_feed
    followees_ids = Follower.where(follower_id: current_user.id).pluck(:following_user_id)

    @photos = Photo.includes(:user).order(created_at: :desc).where(is_public: true)
    .where(user_id: followees_ids).page(params[:page]).per(4)
    @likes = Like.where(likeable_type: 'Photo')
    render "public/feed_photos/index"
  end

  private
  def photo_params
    params.require(:photo).permit(:title, :img_url, :description, :is_public, :user_id)
  end

  def check_user
    if params["id"] === current_user.id.to_s && action_name != 'edit'
      redirect_to photos_path
    end
  end

  def query_navbar(id)
    @user = User.find(id)
    @followees_navbar = Follower.where(following_user_id: id)
    @followers_navbar = Follower.where(follower_id: id)
  end
end

app/helpers/admin/photos_helper.rb
module Admin::PhotosHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/search/photos_helper.rb
module Search::PhotosHelper
end

app/views/admin/photos/edit.html.slim
            div class="main__content__album bg-white mt-4 d-flex flex-column"
                div class="container"
                    div class="text-start fw-3 mt-3"
                        h4 Edit Photo
                    hr
                    div class="main__album d-flex flex-column"
                        form class="row g-3" action="#{photos_path}/#{@photo["id"]}" method="post" enctype="multipart/form-data" accept-charset="UTF-8"
                            = hidden_field_tag :authenticity_token, form_authenticity_token
                            input type="hidden" name="_method" value="patch" autocomplete="off"
                            div class="col-md-6 input__photo"
                                label for="photoTitle" class="form-label"Title
                                input [type="text" class="form-control" id="photoTitle" value="#{@photo["title"]}"
                                    placeholder="Photo Title" name="photo[title]" required]

                            div class="col-md-6 input__photo"
                                label for="photoDescription" class="form-label" Description
                                textarea [class="form-control" id="photoDescription" rows="3"
                                    placeholder="Photo Description" name="photo[description]" required] = @photo["description"]

                            div class="col-md-3"
                                label for="photoMode" class="form-label" Sharing Mode
                                select [class="form-select" id="photoMode" name="photo[is_public]" required value="#{@photo["is_public"]}"]
                                    option [value="1" selected] Public
                                    option value="0" Private

                            div class="col-12"
                                label for="imageSrc" class="form-label"Photo
                                input [type="file" class="form-control" id="file-upload"
                                    accept="image/gif, image/jpeg, image/png, image/jpg" name="photo[img_url]"]
                                input class="photoUrl" type="hidden" value="#{@photo.img_url.url}" name="#{@photo.img_url.identifier}"

                            div class="col-12"
                                div class="preview imgGroup"
                                    img [src="#{@photo.img_url.url}" alt="Preview" id="image-preview"
                                        class="image-preview"]
                            div class="col-12 button-group"
                                button type="submit" class="btn btn-success me-5" Save
                                button id="btn-remove" class="btn btn-danger" Delete

app/views/admin/photos/index.html.slim
    div.main__content__album.bg-white.mt-4.rounded
        div.container.d-flex.flex-column.justify-content-between
            div.main__album.d-flex.flex-column
                div.row
                    - @photos.each do |photo|
                            / <!-- start template -->
                            div.col-2.mb-3.p-0.mx-2.d-flex.flex-column.justify-content-between.shadow.album.position-relative.child-node
                                div.w-100.px-3.py-1.bg-secondary.album__description.text-white.d-flex.justify-content-between
                                    = photo.title
                                    a href="#{edit_admin_photo_path(photo.id)}"
                                       i.fa-solid.fa-lock

                                div.photo.position-absolute.top-0.w-100
                                    img src="#{photo.img_url}" alt=""

                                div.album__lock.px-3.text-end
                                    i.fa-solid.fa-lock
                            / <!-- end template -->
            = render partial: "shared/pagination", locals: {asset: @photos}
    template id="limit_paging_template"
        input.d-none value="10"