config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {
    sign_in: 'sign_in',
    sign_out: 'sign_out',
    password: 'password',
    confirmation: 'confirmation',
    unlock: 'unlock',
    registration: 'registration',
    sign_up: 'sign_up'
  }, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    # passwords: 'custom_passwords',
    confirmations: 'users/confirmations',
    # unlocks: 'custom_unlocks'
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "albums#index_feed"
  get "feeds/photos", to: "photos#index_feed"
  get "pending", to: "pending_users#index"
  scope module: "admin" do
    get "authorizations", to: "authorizations#index"
    get "unauthorized", to: "unauthorizations#index"
  end
  # scope "guest" do
  #   get "authorizations", to: "authorizations#index", as: "guest_authorizations"
  #   get "unauthorized", to: "unauthorizations#index", as: "guest_unauthorizations"
  # end

  # namespace :guest do
  #   get "authorizations", to: "authorizations#index"
  #   get "unauthorized", to: "unauthorizations#index"
  # end
  scope "discovers" do
    get "/", to: "albums#index_discover", as: "discover"
    get "/photos", to: "photos#index_discover", as: "discover_photos"
    get "/photos/:id", to: "photos#discover_user_photos_index", as: "discover_photo"
    get "/albums/:id", to: "albums#discover_user_index", as: "discover_album"
    get "/followees/:id", to: "followees#discover_followee_index", as: "discover_followee"
    get "/followers/:id", to: "followers#discover_follower_index", as: "discover_follower"
  end
  resources :photos, :albums
  resources :followees, only: [:index, :create, :destroy]
  resources :followers, only: [:index, :create, :destroy]
  resources :profiles , only: [:edit, :update]
  resources :passwords , only: [:edit, :update]
  resources :likes, only: [:create, :destroy]
  get 'search', to: "search#index"

  namespace :admin do
    resources :photos, :albums, :users
  end
end

app/views/shared/button/_like.html.slim
= turbo_frame_tag "like-#{asset["id"]}-#{type_asset}"
    - like_found = likes.where(likeable_id: asset["id"])
    - if !current_user.nil?
        - is_found = likes.exists?(user_id: current_user.id, likeable_id: asset["id"])
        form action="#{!is_found ? likes_path : like_path(current_user.id)}" method="post" data-remote="true"
            = hidden_field_tag :authenticity_token, form_authenticity_token
            - if is_found
                input type="hidden" name="_method" value="delete" autocomplete="off"
            input type="hidden" name="like[user_id]" value="#{current_user.id}"
            input type="hidden" name="like[likeable_type]" value="#{type_asset}"
            input type="hidden" name="like[likeable_id]" value="#{asset["id"]}"
            button type="submit" class="photo_heart"
                i class="fa-#{!is_found ? "regular" : "solid"} fa-heart text-primary"
                span.text-primary = like_found.count
    - else
        div.photo_heart
            i class="fa-regular fa-heart text-primary"
            span.text-primary = like_found.count
    / usage
    / = render partial: "shared/button/like", locals: { asset: instance_variable,
    / likes: @class_variable, type_asset: "Album" or "Photo" }