config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {
    sign_in: 'sign_in',
    sign_out: 'sign_out',
    password: 'password',
    confirmation: 'confirmation',
    unlock: 'unlock',
    registration: 'registration',
    sign_up: 'sign_up'
  }, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    # passwords: 'custom_passwords',
    confirmations: 'users/confirmations',
    # unlocks: 'custom_unlocks'
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "albums#index_feed"
  get "feeds/photos", to: "photos#index_feed"
  get "pending", to: "pending_users#index"
  scope module: "admin" do
    get "authorizations", to: "authorizations#index"
    get "unauthorized", to: "unauthorizations#index"
  end
  # scope "guest" do
  #   get "authorizations", to: "authorizations#index", as: "guest_authorizations"
  #   get "unauthorized", to: "unauthorizations#index", as: "guest_unauthorizations"
  # end

  # namespace :guest do
  #   get "authorizations", to: "authorizations#index"
  #   get "unauthorized", to: "unauthorizations#index"
  # end
  scope "discovers" do
    get "/", to: "albums#index_discover", as: "discover"
    get "/photos", to: "photos#index_discover", as: "discover_photos"
    get "/photos/:id", to: "photos#discover_user_photos_index", as: "discover_photo"
    get "/albums/:id", to: "albums#discover_user_index", as: "discover_album"
    get "/followees/:id", to: "followees#discover_followee_index", as: "discover_followee"
    get "/followers/:id", to: "followers#discover_follower_index", as: "discover_follower"
  end
  resources :photos, :albums
  resources :followees, only: [:index, :create, :destroy]
  resources :followers, only: [:index, :create, :destroy]
  resources :profiles , only: [:edit, :update]
  resources :passwords , only: [:edit, :update]
  resources :likes, only: [:create, :destroy]
  get 'search', to: "search#index"

  namespace :admin do
    resources :photos, :albums, :users
  end
end

app/views/shared/navbar/_followee_navbar.html.slim
    = turbo_frame_tag "followee_tab"
        span #{followers_count} Followings
    / usage
    / = render partial: "shared/navbar/followee_navbar", locals: {followers_count: instance_variable}

app/views/shared/navbar/_follower_navbar.html.slim
    = turbo_frame_tag "follower_tab"
        span #{followees_count} Followers
    / usage
    / = render partial: "shared/navbar/follower_navbar", locals: {followees_count: instance_variable}

app/views/shared/navbar/_index.html.slim
    nav.navbar.navbar-expand-lg.bg-body-tertiary.align-items-start.mt-4
        div.container-fluid.justify-content-center.mt-4.pb-4
            div.navbar-nav.navbar-responsive.flex-column
                div.line.mb-1.bg-black
                div.line.mb-1.bg-black
                div.line.mb-1.bg-black

            div class="navbar-nav navbar-normal flex-column"
                = link_to "Feeds", root_path, class: "nav-link #{request.path == root_path || request.path == feeds_photos_path ? 'active' : ''}"
                = link_to "Discover", discover_path, class: "nav-link #{request.path == discover_path || request.path == discover_photos_path ? 'active' : ''}"
        / usage
        / = render partial: 'shared/navbar/index'

app/views/shared/navbar/_profile_navbar.html.slim
    div class="profile__nav d-flex"
        div class="profile__img"
            img src="#{user.img_url.present? ? user.img_url.url : '/assets/avatar.png'}" alt=""
        div class="profile__info d-flex flex-column justify-content-between ms-4"
            div
                a class="btn btn-edit-profile btn-sm w-25" href="#{edit_user_registration_path}" Edit Profile
                - if current_user.user_type == 'admin'
                    a class="btn btn-edit-profile btn-sm w-25" href="#{admin_photos_path}" Adminitrative
            h1 = user.first_name.to_s.humanize + ' ' + user.last_name.to_s.humanize
            nav class="tabs d-flex fs-5 p-0"
                a class="tab #{request.path == photos_path ? 'active':''} ps-0 ms-0" href="#{photos_path}"
                    span #{photo_count} Photos
                a class="tab #{request.path == albums_path ? 'active':''}" href="#{albums_path}"
                    span #{album_count} Albums
                a class="tab #{request.path == followees_path ? 'active':''}" href="#{followees_path}"
                    = render partial: "shared/navbar/followee_navbar", locals: { followers_count: followers.count }
                a class="tab #{request.path == followers_path ? 'active':''}" href="#{followers_path}"
                    span #{followees.count} Followers
                / usage
                / = render partial: "shared/profile_navbar", locals: {user: @class_variable, album_count: instance_variable,
                /     photo_count: instance_variable,
                /     followees: @class_variable,
                /     followers: @class_variable}

app/views/shared/navbar/_user_navbar.html.slim
    div class="profile__nav d-flex"
        div class="profile__img"
            img src="#{user.img_url.present? ? user.img_url.url : '/assets/avatar.png'}" alt=""
        div class="profile__info d-flex flex-column justify-content-between ms-4"
            = render partial: "shared/button/follow/user", locals: {followees: followees, user_id: user.id}
            h1 = user.first_name.to_s.humanize + ' ' + user.last_name.to_s.humanize
            nav class="tabs d-flex fs-5 p-0"
                a class="tab #{request.path == discover_photo_path(params["id"]) ? 'active':''} ps-0 ms-0" href="#{discover_photo_path(params["id"])}"
                    span #{photo_count} Photos
                a class="tab #{request.path == discover_album_path(params["id"]) ? 'active':''}" href="#{discover_album_path(params["id"])}"
                    span #{album_count} Albums
                a class="tab #{request.path == discover_followee_path(params["id"]) ? 'active':''}" href="#{discover_followee_path(params["id"])}"
                    span #{followers.count} Followings
                a class="tab #{request.path == discover_follower_path(params["id"]) ? 'active':''}" href="#{discover_follower_path(params["id"])}"
                    = render partial: "shared/navbar/follower_navbar", locals: { followees_count: followees.count }
                / usage
                / = render partial: "shared/user_navbar", locals: {user: @class_variable, album_count: instance_variable,
                /     photo_count: instance_variable,
                /     followees: @class_variable,
                /     followers: @class_variable}